algoritmo "Ex15"
var
   dias_trabalhados: inteiro
   valor, salario: real
inicio
      Escreva("Me informe os duas trabalhados: ")
      Leia(dias_trabalhados)
      valor <- 8 * 25
      salario <- dias_trabalhados * valor
      Escreva("Seu salário é:", salario)
fimalgoritmo

//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.