algoritmo "Ex3"
var
   salario: real
   nome: caractere
inicio
      Escreva("Nome do Funcionário: ")
      Leia(nome)
      Escreva("Salário: ")
      Leia(salario)
      Escreva("O funcionario ",nome," tem um salário de R$",salario," em Junho")
fimalgoritmo

//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.