algoritmo "Ex4"
var
   valor1, valor2, soma: real
inicio
      Escreva("Digite um valor: ")
      leia(valor1)
      Escreva("Digite outro valor: ")
      leia(valor2)
      soma <- valor1 + valor2
      Escreva("A soma entre",valor1," e",valor2," é igual a",soma)
fimalgoritmo

//4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.