algoritmo "Ex7"
var
   num, dobro, terca: real
inicio
      Escreva("Digite um número: ")
      Leia(num)
      dobro <- num * 2
      terca <- num / 3
      Escreval("O dobro de",num," é",dobro)
      Escreval("A terça parte de",num," é ",terca:1:5)
fimalgoritmo

//7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666