algoritmo "Ex66"
var
   i: inteiro
   valor: inteiro
inicio

      Escreva("Digite um valor: ")
      Leia(valor)
      
   para i <- 1 até 10 faca
      escreval(valor, " X ", i, " = ", valor * i )
   fimpara
fimalgoritmo

//66) Escreva um programa que leia um número qualquer e mostre a tabuada desse
//número, usando a estrutura “para”.
//Ex: Digite um valor: 5
//5 x 1 = 5
//5 x 2 = 10
//5 x 3 = 15 ...
